# .streamlit/secrets.toml
[mongo]
connection_string = "mongodb+srv://galileolovenewton_db_user:Galileo200337@cluster0.rhzzift.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
db_name = "hr_dashboard"
collection_name = "market_jobs"